[2025-02-28T22:22:52.339+0200] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-28T22:22:52.343+0200] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_token_processing.analyze_tokens scheduled__2025-02-28T20:10:00+00:00 [queued]>
[2025-02-28T22:22:52.346+0200] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_token_processing.analyze_tokens scheduled__2025-02-28T20:10:00+00:00 [queued]>
[2025-02-28T22:22:52.346+0200] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-28T22:22:52.350+0200] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): analyze_tokens> on 2025-02-28 20:10:00+00:00
[2025-02-28T22:22:52.356+0200] {logging_mixin.py:190} WARNING - /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=17107) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-28T22:22:52.356+0200] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'kafka_token_processing', 'analyze_tokens', 'scheduled__2025-02-28T20:10:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/kafka_token_processing.py', '--cfg-path', '/var/folders/dw/z1bbk7h952586r5vt211lpjc0000gn/T/tmpzynwdddu']
[2025-02-28T22:22:52.357+0200] {standard_task_runner.py:72} INFO - Started process 17113 to run task
[2025-02-28T22:22:52.357+0200] {standard_task_runner.py:105} INFO - Job 14: Subtask analyze_tokens
[2025-02-28T22:22:52.380+0200] {task_command.py:467} INFO - Running <TaskInstance: kafka_token_processing.analyze_tokens scheduled__2025-02-28T20:10:00+00:00 [running]> on host nams-macbook-air.local
[2025-02-28T22:22:52.400+0200] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='kafka_token_processing' AIRFLOW_CTX_TASK_ID='analyze_tokens' AIRFLOW_CTX_EXECUTION_DATE='2025-02-28T20:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-28T20:10:00+00:00'
[2025-02-28T22:22:52.400+0200] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-28T22:22:52.400+0200] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-28T22:22:52.401+0200] {logging_mixin.py:190} INFO - Current task name:analyze_tokens state:running start_date:2025-02-28 20:22:52.343978+00:00
[2025-02-28T22:22:52.401+0200] {logging_mixin.py:190} INFO - Dag name:kafka_token_processing and current dag run status:running
[2025-02-28T22:22:52.401+0200] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-28T22:22:52.401+0200] {kafka_token_processing.py:48} INFO - Running analytics task...
[2025-02-28T22:22:52.924+0200] {kafka_token_processing.py:54} ERROR - Error running analytics script: Command '['python3', '/Users/nampham/git_repos/self-develop/kafka-airflow/token_analysis.py']' returned non-zero exit status 1.
[2025-02-28T22:22:52.925+0200] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nampham/git_repos/self-develop/kafka-airflow/airflow/dags/kafka_token_processing.py", line 51, in analytics_task
    result = subprocess.run(["python3", "/Users/nampham/git_repos/self-develop/kafka-airflow/token_analysis.py"], check=True, capture_output=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/subprocess.py", line 573, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', '/Users/nampham/git_repos/self-develop/kafka-airflow/token_analysis.py']' returned non-zero exit status 1.
[2025-02-28T22:22:52.933+0200] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-28T22:22:52.934+0200] {logging_mixin.py:190} INFO - Task start:2025-02-28 20:22:52.343978+00:00 end:2025-02-28 20:22:52.933701+00:00 duration:0.589723
[2025-02-28T22:22:52.934+0200] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): analyze_tokens> dag:<DAG: kafka_token_processing> dagrun:<DagRun kafka_token_processing @ 2025-02-28 20:10:00+00:00: scheduled__2025-02-28T20:10:00+00:00, state:running, queued_at: 2025-02-28 20:15:02.507541+00:00. externally triggered: False>
[2025-02-28T22:22:52.934+0200] {logging_mixin.py:190} INFO - Failure caused by Command '['python3', '/Users/nampham/git_repos/self-develop/kafka-airflow/token_analysis.py']' returned non-zero exit status 1.
[2025-02-28T22:22:52.935+0200] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=kafka_token_processing, task_id=analyze_tokens, run_id=scheduled__2025-02-28T20:10:00+00:00, execution_date=20250228T201000, start_date=20250228T202252, end_date=20250228T202252
[2025-02-28T22:22:52.941+0200] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-28T22:22:52.941+0200] {standard_task_runner.py:124} ERROR - Failed to execute job 14 for task analyze_tokens (Command '['python3', '/Users/nampham/git_repos/self-develop/kafka-airflow/token_analysis.py']' returned non-zero exit status 1.; 17113)
Traceback (most recent call last):
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nampham/git_repos/self-develop/kafka-airflow/airflow/dags/kafka_token_processing.py", line 51, in analytics_task
    result = subprocess.run(["python3", "/Users/nampham/git_repos/self-develop/kafka-airflow/token_analysis.py"], check=True, capture_output=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/subprocess.py", line 573, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', '/Users/nampham/git_repos/self-develop/kafka-airflow/token_analysis.py']' returned non-zero exit status 1.
[2025-02-28T22:22:52.970+0200] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-28T22:22:52.977+0200] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-28T22:22:52.977+0200] {local_task_job_runner.py:245} INFO - ::endgroup::
